CREATE TABLE users (
    `id` INT NOT NULL,
    `gpa` INT,
    `firstname` VARCHAR(20) NOT NULL,
    `lastname` VARCHAR(20) NOT NULL,
    `username` VARCHAR(25) NOT NULL,
    `salt` VARCHAR(32) NOT NULL,
    `password` VARCHAR(40) NOT NULL,
    `year` INT NOT NULL,
    `degree` VARCHAR(30) NOT NULL,
    `major` VARCHAR(30) NOT NULL,
    `instrument` VARCHAR(30) NOT NULL,
    `con_instrument` VARCHAR(30) NOT NULL,
    `title` VARCHAR(10),
    `phone` VARCHAR(10),
    `cell` VARCHAR(10),
    `email` VARCHAR(50),
    `address_1` VARCHAR(50),
    `address_2` VARCHAR(50),
    `city` VARCHAR(15),
    `postal_code` VARCHAR(15),
    `country` VARCHAR(30),
    `status` TINYINT(1) DEFAULT 0,
    `last_midified_by_student` DATETIME,
    `last_reviewed_by_staff` DATETIME,
    `permission_to_publish_personal_info` TINYINT(1) DEFAULT 0,
    `discr` VARCHAR(30) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (username)
) ENGINE = InnoDB;
