jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
        Prooms\SecurityBundle\Entity\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
        Prooms\SecurityBundle\Entity\Student:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
        Prooms\SecurityBundle\Entity\Staff:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                provider: [in_memory, user_db]
        user_db:
            entity: { class: Prooms\SecurityBundle\Entity\User, property: username }
        in_memory:
            memory:
                users:
                    ryan:  { password: bb87a29949f3a1ee0559f8a57357487151281386, roles: [ 'ROLE_STAFF' ] }

    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /rooms/list
            logout:
                path: logout
                target: /rooms/list
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
