parameters:
#    prooms_rooms.example.class: Prooms\RoomsBundle\Example

services:
#    prooms_rooms.example:
#        class: %prooms_rooms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
